# Generated by Django 5.0.7 on 2024-07-19 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IOTControllerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "device_id",
                    models.UUIDField(default=uuid.uuid4, verbose_name="Unique UUID"),
                ),
                ("device_name", models.CharField(max_length=255)),
                (
                    "device_status",
                    models.IntegerField(
                        choices=[(0, "OFF"), (1, "ZOM"), (2, "ON")], default=-1
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="زمان آخرین تغییرات"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ایجاد"),
                ),
                (
                    "auther",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="سازنده",
                    ),
                ),
            ],
            options={
                "db_table": "iot_controller",
            },
        ),
    ]
